function saveResults(results, names, threads, filename)

fid = fopen(filename,'w');

if fid ~= -1
    for i = 1:numel(results)
        fprintf(fid,[names{i} '\n']);
        fprintf(fid, "threads, min, max, mean, std, prtcl_90, prctl_95, prctl_99, prctl_99.99, throughput\n");
        
        for j = 1:numel(results{i})
            fprintf(fid, "%d, %d, %d, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f, %.2f\n",...
                threads(j),...
                results{i}(j).min,...
                results{i}(j).max,...
                results{i}(j).mean,...
                results{i}(j).std,...
                results{i}(j).percentiles(1),...
                results{i}(j).percentiles(2),...
                results{i}(j).percentiles(3),...
                results{i}(j).percentiles(4),...
                results{i}(j).throughput);
        end
    end
    fclose(fid);
end

end

